#!/bin/bash
#
# chkconfig: 35 90 12
# description: firewall-auth
#
# Get function from functions library
# . /etc/init.d/functions

APPNAME="auth"

# Start the service firewall-auth
start() {
        /home/srijan/Documents/firewall-auth &>/dev/null &
}

# Restart the service firewall-auth
stop() {
        pkill auth
}

### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status firewall-auth
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
